name: Deploy Static Site to EC2

on:
  push:
    branches:
      - dev
      - stg
      - main
  pull_request:
    branches:
      - dev
      - stg
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy site to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.48.133.233 "mkdir -p ~/site"
          scp -r site/* ubuntu@13.48.133.233:~/site/

      - name: Restart web server
        run: |
          ssh ubuntu@13.48.133.233 "sudo systemctl restart nginx"

